<?php
$pageTitle = 'Hỗ trợ - ' . ($settings['site_title'] ?? 'VC VPN 2027');
$items = is_array($tickets ?? null) ? $tickets : [];
$labels = ['open' => 'Đang chờ', 'in_progress' => 'Đang xử lý', 'resolved' => 'Đã giải quyết', 'closed' => 'Đã đóng'];
ob_start();
?>
<section class="user-record-page"><header class="user-orders-header"><div class="user-orders-intro"><h2 style="color: #020af4; font-family: emoji;">TRUNG TÂM HỖ TRỢ</h2><p>Gửi và theo dõi yêu cầu hỗ trợ của bạn.</p></div><div class="user-orders-title-row"><h1>Hỗ trợ</h1><a class="glass-btn" href="/tickets/create">Tạo yêu cầu</a></div></header>
<?php if (!empty($_SESSION['success']) || !empty($_SESSION['error'])): ?><div class="user-record-alert <?= !empty($_SESSION['error']) ? 'is-error' : '' ?>"><span><?= htmlspecialchars($_SESSION['error'] ?? $_SESSION['success']) ?></span><button type="button" class="alert-close-btn" onclick="this.parentElement.remove();" aria-label="Đóng">&times;</button></div><?php unset($_SESSION['success'], $_SESSION['error']); endif; ?>
<?php if ($items): ?><div class="glass-card user-record-table-wrap"><table class="user-record-table"><thead><tr><th>Tiêu đề</th><th>Trạng thái</th><th>Nhân viên</th><th>Ngày tạo</th><th style="text-align: right;">Thao tác</th></tr></thead><tbody><?php foreach ($items as $item): ?><?php $status = $item['status'] ?? 'open'; ?><tr><td data-label="Tiêu đề"><strong><?= htmlspecialchars($item['subject'] ?? '') ?></strong></td><td data-label="Trạng thái"><span class="user-record-status is-<?= htmlspecialchars($status) ?>"><?= htmlspecialchars($labels[$status] ?? $status) ?></span></td><td data-label="Nhân viên"><?= htmlspecialchars($item['staff_name'] ?? 'Chưa phân công') ?></td><td data-label="Ngày tạo"><?= !empty($item['created_at']) ? date('d/m/Y H:i', strtotime($item['created_at'])) : '-' ?></td><td class="user-record-action" style="text-align: right;"><div class="action-dropdown"><button type="button" class="action-btn" title="Thao tác">☰</button><div class="action-menu" style="min-width: 155px; white-space: nowrap;"><a href="/tickets/detail?id=<?= (int) ($item['id'] ?? 0) ?>" class="action-item"><span>👁️</span> Xem chi tiết</a><?php if ($status !== 'closed'): ?><form method="post" action="/tickets/close" style="margin: 0;" data-confirm-submit="Bạn có chắc muốn hủy/đóng yêu cầu hỗ trợ này?"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf_token ?? '') ?>"><input type="hidden" name="ticket_id" value="<?= (int) ($item['id'] ?? 0) ?>"><button type="submit" class="action-item cancel" style="color: var(--ios-danger);"><span>❌</span> Hủy yêu cầu</button></form><?php endif; ?></div></div></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="glass-card user-record-empty"><h2>Chưa có yêu cầu hỗ trợ</h2><p>Khi cần trợ giúp, hãy tạo yêu cầu để đội ngũ hỗ trợ phản hồi.</p><a href="/tickets/create" class="glass-btn">Tạo yêu cầu</a></div><?php endif; ?></section>
<?php $content = ob_get_clean(); $showSidebar = true; require_once __DIR__ . '/../../layouts/app.php'; ?>
